export enum AUTH_ACTION_TYPES {
    STARTED_REQUEST_REGISTER = 'STARTED_REQUEST_REGISTER',
    REQUEST_REGISTER_SUCCESS = 'STARTED_REQUEST_REGISTER',
    REQUEST_REGISTER_FAILURE = 'REQUEST_REGISTER_FAILURE',

    STARTED_REQUEST_LOGIN = 'STARTED_REQUEST_LOGIN',
    REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS',
    REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE',
}