export enum AUTH_ACTION_TYPES {
    STARTED_REQUEST_REGISTER = 'STARTED_REQUEST_REGISTER',
    REQUEST_REGISTER_SUCCESS = 'STARTED_REQUEST_REGISTER',
    REQUEST_REGISTER_FAILURE = 'REQUEST_REGISTER_FAILURE',
}