export enum AUTH_ACTION_TYPES {
    STARTED_REQUEST_REGISTER = 'STARTED_REQUEST_REGISTER',
    REQUEST_REGISTER_SUCCESS = 'REQUEST_REGISTER_SUCCESS',
    REQUEST_REGISTER_FAILURE = 'REQUEST_REGISTER_FAILURE',

    STARTED_REQUEST_VERIFICATION = 'STARTED_REQUEST_VERIFICATION',
    REQUEST_VERIFICATION_SUCCESS = 'REQUEST_VERIFICATION_SUCCESS',
    REQUEST_VERIFICATION_FAILURE = 'REQUEST_VERIFICATION_FAILURE',

    STARTED_REQUEST_LOGIN = 'STARTED_REQUEST_LOGIN',
    REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS',
    REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE',

    STARTED_REQUEST_SEND_MESSAGE_CODE_EDIT_PROFILE = 'STARTED_REQUEST_SEND_MESSAGE_CODE_EDIT_PROFILE',
    REQUEST_SEND_MESSAGE_CODE_EDIT_PROFILE_SUCCESS = 'REQUEST_SEND_MESSAGE_CODE_EDIT_PROFILE_SUCCESS',
    REQUEST_SEND_MESSAGE_CODE_EDIT_PROFILE_FAILURE = 'REQUEST_SEND_MESSAGE_CODE_EDIT_PROFILE_FAILURE',

    STARTED_REQUEST_EDIT_PROFILE = 'STARTED_REQUEST_EDIT_PROFILE',
    REQUEST_EDIT_PROFILE_SUCCESS = 'REQUEST_EDIT_PROFILE_SUCCESS',
    REQUEST_EDIT_PROFILE_FAILURE = 'REQUEST_EDIT_PROFILE_FAILURE',
}